env:
  TERM: xterm-256color
window:
  opacity: 1
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 2
    y: 2

  dynamic_padding: false
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #     - buttonless: Title bar, transparent background and title bar buttons
  #     - transparent: Title bar, transparent background, but no title bar buttons
  decorations: none
  
  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: SimpleFullscreen

# scrolling.multiplier: 3

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 5000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 1

  # Scroll to the bottom when new text is written to the terminal.
  auto_scroll: true

# Display tabs using this many cells (changes require restart)
tabspaces: 4

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: "FiraCode Nerd Font"
    # family: "MesloLGS Nerd Font"
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: "FiraCode Nerd Font"
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: "FiraCode Nerd Font"
    # Style can be specified to pick a specific face.
    style: Italic

  # Point size of the font
  size: 22.0

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.test_test1
  glyph_offset:
    x: 0
    y: 0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  # use_thin_strokes: false

#debug:
  ## Display the time it takes to redraw each frame.
  #render_timer: false

  ## Keep the log file after quitting Alacritty.
  #persistent_logging: false

  ## Log level
  ##
  ## Values for `log_level`:
  ##   - None
  ##   - Error
  ##   - Warn
  ##   - Info
  ##   - Debug
  ##   - Trace
  #log_level: Warn

  ## Print all received window events.
  #print_events: false

  ## Record all characters and escape sequences as test data.
  #ref_test: false


## Colors (Pink Moon)
#colors:
  ## Default colors
  #primary:
  #  background: '0x2a2e38'
  #  foreground: '0xF0FDFF'

  #  # (Optional) Bright and Dim foreground colors
  #  #
  #  # The dimmed foreground color is calculated automatically if it is not present.
  #  # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
  #  # is `false`, the normal foreground color will be used.
  #  #
  #  # dim_foreground: '0x9a9a9a'
  #  # bright_foreground: '0xffffff'


# Kanagawa Alacritty Colors
colors:
  primary:
    background: '0x16161D'
    foreground: '0xdcd7ba'

  normal:
    black:   '0x090618'
    red:     '0xc34043'
    green:   '0x76946a'
    yellow:  '0xc0a36e'
    blue:    '0x7e9cd8'
    magenta: '0x957fb8'
    cyan:    '0x6a9589'
    white:   '0xc8c093'

  bright:
    black:   '0x727169'
    red:     '0xe82424'
    green:   '0x98bb6c'
    yellow:  '0xe6c384'
    blue:    '0x7fb4ca'
    magenta: '0x938aa9'
    cyan:    '0x7aa89f'
    white:   '0xdcd7ba'

  selection:
    background: '0x2d4f67'
    foreground: '0xc8c093'

  indexed_colors:
    - { index: 16, color: '0xffa066' }
    - { index: 17, color: '0xff5d62' }
    
## Visual Bell
##
## Any time the BEL code is received, Alacritty "rings" the visual bell. Once
## rung, the terminal background will be set to white and transition back to the
## default background color. You can control the rate of this transition by
## setting the `duration` property (represented in milliseconds). You can also
## configure the transition function by setting the `animation` property.
##
## Possible values for `animation`
## `Ease`
## `EaseOut`
## `EaseOutSine`
## `EaseOutQuad`
## `EaseOutCubic`
## `EaseOutQuart`
## `EaseOutQuint`
## `EaseOutExpo`
## `EaseOutCirc`
## `Linear`
##
## To completely disable the visual bell, set its duration to 0.
##
# visual_bell:
#   animation: EaseOutExpo
#   duration: 1


## Mouse bindings
##
## Currently doesn't support modifiers. Both the `mouse` and `action` fields must
## be specified.
##
## Values for `mouse`:
## - Middle
## - Left
## - Right
## - Numeric identifier such as `5`
##
## Values for `action`:
## - Paste
## - PasteSelection
## - Copy (TODO)
#mouse_bindings:
  #- { mouse: Middle, action: PasteSelection }

#mouse:
  ## Click settings
  ##
  ## The `double_click` and `triple_click` settings control the time
  ## alacritty should wait for accepting multiple clicks as one double
  ## or triple click.
  #double_click: { threshold: 300 }
  #triple_click: { threshold: 300 }

  #hide_when_typing: false
  ## Faux Scrollback
  ##
  ## The `faux_scrollback_lines` setting controls the number
  ## of lines the terminal should scroll when the alternate
  ## screen buffer is active. This is used to allow mouse
  ## scrolling for applications like `man`.
  ##
  ## To disable this completely, set `faux_scrollback_lines` to 0.
  ## faux_scrollback_lines: 1

  #url:
  #    # URL launcher
  #    #
  #    # This program is executed when clicking on a text which is recognized as a URL.
  #    # The URL is always added to the command as the last parameter.
  #    launcher: open

  #    # URL modifiers
  #    #
  #    # These are the modifiers that need to be held down for opening URLs when clicking
  #    # on them. The available modifiers are documented in the key binding section.
  #    #modifiers: Control|Shift

#selection:
  #semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  
  ## When set to `true`, selected text will be copied to the primary clipboard.
  #save_to_clipboard: false

#dynamic_title: true


cursor:
  # Style of the cursor
  #
  # Values for 'cursor_style':
  # - Block
  # - Underline
  # - Beam
  style: Block

  ## Whether the cursor should be a hollow block on window focus loss
  unfocused_hollow: true

## Live config reload (changes require restart)
#live_config_reload: true

## Shell
##
## You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
## Entries in shell.args are passed unmodified as arguments to the shell.
##
# ## shell:
# ##   program: /bin/bash
# ##   args:
# ##     - --login

# shell:
#   program: /opt/homebrew/bin/zsh
  #args:
  #  - -c
  #  - cd ~/Documents/code && exec bash
